networks:
  external-network:
    external: true

volumes:
  node_modules:

services:
  video:
    image: home-brew-plex
    build: ./
    container_name: home-brew-plex
    restart: always
    ports:
      - "4000:4000"
    networks:
      - external-network
    volumes:
      - ./:/src
      - node_modules:/src/node_modules